
name : push

on: [ push ]

jobs :

  build :
    if: "startsWith( github.event.head_commit.message, 'version' ) && startsWith( github.ref, 'refs/tags/v' )"
    uses : dmvict/Test/.github/workflows/Linux.yml@master

  # last :
  #   needs: [ build ]
  #   if: startsWith( github.ref, 'refs/tags/v' )
  #   runs-on : ubuntu-latest
  #   steps :
  #     - uses: actions/checkout@v2
  #     - run: rm -rf out/*
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: ubuntu
  #         path: out/linux_release
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: macos
  #         path: out/macos_release
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: windows
  #         path: out/windows_release
  #     - name: Pushes to another repository
  #       uses: cpina/github-action-push-to-another-repository@main
  #       env:
  #         API_TOKEN_GITHUB: ${{ secrets.PRIVATE_TOKEN }}
  #       with:
  #         source-directory: out
  #         target-directory: out/${{ github.ref_name }}
  #         destination-github-username: 'dmvict'
  #         destination-repository-name: 'test-push'
  #         user-email: dm.vict.kr@gmail.com
  #         target-branch: master
  #     - run: git checkout out/
  #     - run: rm -rf out/*
  #     - run: echo '[linux](https://github.com/dmvict/test-push/raw/master/out/${{ github.ref_name }}/linux_release/test)' >> out/${{ github.ref_name }}.md
  #     - run: echo ' ' >> out/${{ github.ref_name }}.md
  #     - run: echo '[macos](https://github.com/dmvict/test-push/raw/master/out/${{ github.ref_name }}/macos_release/test)' >> out/${{ github.ref_name }}.md
  #     - run: echo ' ' >> out/${{ github.ref_name }}.md
  #     - run: echo '[windows](https://github.com/dmvict/test-push/raw/master/out/${{ github.ref_name }}/windows_release)' >> out/${{ github.ref_name }}.md
  #     - uses: quizlet/commit-changes@v0.2.0
  #       with:
  #         token: ${{ secrets.PRIVATE_TOKEN }}
  #         message: Automated commit
  #         glob-patterns: out/

  publish:
    needs: [ build ]
    if: "startsWith( github.event.head_commit.message, 'version' ) && startsWith( github.ref, 'refs/tags/v' )"
    runs-on: ubuntu-latest
    env :
      PRIVATE_TOKEN : ${{ secrets.PRIVATE_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p exp
      - run: cp -R out exp
      - run: cp Cargo.toml exp/Cargo.toml
      - run: cp README.md exp/Readme.md
      - name: Publish changes in release repo
        uses: vinayb21/github-action-push-to-another-repo@1.4.0
        env:
          API_TOKEN_GITHUB: ${{ secrets.PRIVATE_TOKEN }}
        with:
          source-directory: exp
          destination-github-username: dmvict
          destination-repository-name: test-push
          user-email: dm.vict.kr@gmail.com
          commit-message: ${{ github.event.head_commit.message }}
          tag: ${{ github.ref_name }}
      - uses: alice-biometrics/release-creator/@v1.0.5
        with:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
          version: ${{ github.ref_name }}
          description: 'Release from development repository: ${{ github.repository }}'
          repo: test-push
          branch: master
          prerelease: false
          draft: false

