
name : command

on: push

jobs :

  build :
    runs-on: ubuntu-latest
    steps :
      - uses: actions/checkout@v2
      - uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
        with:
          SSHKEY: ${{ secrets.SSH_SECRET }}
          ORIGIN: ${{ secrets.HOST }}
          NAME: id_rsa
          PORT: ${{ secrets.PORT }}
          USER: ${{ secrets.USER }}
      - run : sudo apt install sshfs
      - run : cargo build
      - run : mkdir mnt
      - run : sshfs ${{ secrets.COMMAND }} ./mnt
      - run : mkdir -p ./mnt/out/v1
      - run : cp -R target/debug ./mnt/out/v1
      - run : umount ./mnt

