
name : command

on: push

jobs :

  build :
    runs-on: ubuntu-latest
    steps :
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_SECRET }}
      - run : sudo apt install sshfs
      - run : cargo build
      - run : mkdir mnt
      - run : sshfs ${{ secrets.COMMAND }} ./mnt
      - run : mkdir -p ./mnt/out/v1
      - run : cp -R target/debug ./mnt/out/v1
      - run : umount ./mnt

