
name : command

on: push

jobs :

  build :
    runs-on: ubuntu-latest
    steps :
      - uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_SECRET }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN }}
      - run : sudo apt install sshfs
      - run : cargo build
      - run : mkdir mnt
      - run : sshfs ${{ secrets.COMMAND }} ./mnt
      - run : mkdir -p ./mnt/out/v1
      - run : cp -R target/debug ./mnt/out/v1
      - run : umount ./mnt
