
name: Delete
on: [ push ]

jobs:
  del_runs:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Delete workflow runs
        uses: dmvict/clean-action@master
