
name: Delete
on:
  workflow_dispatch:
    inputs:
      days:
        older-than-seconds: 'Delete older than the number of days.'
        required: true
        type: number
        default: 90

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.PRIVATE_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: ${{ github.event.inputs.days }}
