
name : linux

on: [ push ]

jobs :

  build :
    runs-on: ubuntu-latest
    steps :
      - uses: actions/checkout@v2
      - name: Open Pr
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
          PULL_REQUEST_BRANCH: alpha
          PULL_REQUEST_TITLE: 'READY : Forward changes from beta to master'
          PASS_IF_EXISTS: true
