
name : push

on:
  workflow_call:
    inputs:
      commit:
        required: true
        type: string

jobs :

  build :
    runs-on : ubuntu-latest
    steps :
      - run : echo one
      - name: conditional
        if: ${{ inputs.commit != 'false' }}
        run: echo conditional

